In [13]:
import os
import pandas as pd
from scipy.stats import f_oneway

# Folder path and sensors
folder_path = r'C:\Users\rusha\Desktop\Uni_Freiburg_Notes\MDD\pilot\standard_images'
sensors = ['accelerometer', 'bvp', 'eda', 'systolicPeaks', 'temperature']

# Dictionary to hold dataframes for each subject and sensor
subject_dataframes = {subject: {sensor: pd.DataFrame() for sensor in sensors} for subject in ['1', '2', '3']}

# Loop through each subject folder
for subject_folder in os.listdir(folder_path):
    subject_path = os.path.join(folder_path, subject_folder)
    if os.path.isdir(subject_path) and subject_folder in subject_dataframes:
        for sensor in sensors:
            file_path = os.path.join(subject_path, f'{sensor}.csv')
            if os.path.isfile(file_path):
                df = pd.read_csv(file_path)
                df['subject'] = subject_folder
                df['sensor'] = sensor
                
                # Store the dataframe in the appropriate location
                subject_dataframes[subject_folder][sensor] = df

# subject 1:
df_accelerometer_1 = subject_dataframes['1']['accelerometer']
df_bvp_1 = subject_dataframes['1']['bvp']
df_eda_1 = subject_dataframes['1']['eda']
df_temperature_1 = subject_dataframes['1']['temperature']

# subject 2:
df_accelerometer_2 = subject_dataframes['2']['accelerometer']
df_bvp_2 = subject_dataframes['2']['bvp']
df_eda_2 = subject_dataframes['2']['eda']
df_temperature_2 = subject_dataframes['2']['temperature']

# subject 3:
df_accelerometer_3 = subject_dataframes['3']['accelerometer']
df_bvp_3 = subject_dataframes['3']['bvp']
df_eda_3 = subject_dataframes['3']['eda']
df_temperature_3 = subject_dataframes['3']['temperature']

In [14]:
def merge_dataframes(dfs, on='time'):
    result = dfs.pop(0)
    for df in dfs:
        result = pd.merge(result, df, on=on, how='outer', suffixes=('', '_dup'))
        result = result.loc[:, ~result.columns.duplicated()]
    return result

combined_dataframes = {}
for subject, dfs in subject_dataframes.items():
    for sensor, df in dfs.items():
        if 'time' not in df.columns:
    
            df['time'] = pd.to_datetime(df.index, unit='s')
    
  
    combined_df = pd.concat(list(dfs.values()))
    
    combined_dataframes[subject] = combined_df

df_combined_1 = combined_dataframes['1']
df_combined_2 = combined_dataframes['2']
df_combined_3 = combined_dataframes['3']

In [15]:
df_eda_2

        values          time subject sensor
0     0.053166  1.711122e+09       2    eda
1     0.052846  1.711122e+09       2    eda
2     0.055023  1.711122e+09       2    eda
3     0.054211  1.711122e+09       2    eda
4     0.055343  1.711122e+09       2    eda
...        ...           ...     ...    ...
1383  0.072701  1.711122e+09       2    eda
1384  0.072164  1.711122e+09       2    eda
1385  0.074950  1.711122e+09       2    eda
1386  0.076344  1.711122e+09       2    eda
1387  0.073441  1.711122e+09       2    eda

[1388 rows x 4 columns]

In [16]:
# df_accelerometer_1 = df_accelerometer_1.drop(columns=['subject', 'sensor'])
# df_accelerometer_2 = df_accelerometer_2.drop(columns=['subject', 'sensor'])
# df_accelerometer_3 = df_accelerometer_3.drop(columns=['subject', 'sensor'])
# df_bvp_1 = df_bvp_1.drop(columns=['subject', 'sensor'])
# df_bvp_2 = df_bvp_2.drop(columns=['subject', 'sensor'])
# df_bvp_3 = df_bvp_3.drop(columns=['subject', 'sensor'])
# df_eda_1 = df_eda_1.drop(columns=['subject', 'sensor'])
# df_eda_2 = df_eda_2.drop(columns=['subject', 'sensor'])
# df_eda_3 = df_eda_3.drop(columns=['subject', 'sensor'])
# df_temperature_1 = df_temperature_1.drop(columns=['subject', 'sensor'])
# df_temperature_2 = df_temperature_2.drop(columns=['subject', 'sensor'])
# df_temperature_3 = df_temperature_3.drop(columns=['subject', 'sensor'])

In [17]:
df_accelerometer_3

           x      y       z          time subject         sensor
0     -175.0  702.0  1920.0  1.711124e+09       3  accelerometer
1     -192.0  690.0  1919.0  1.711124e+09       3  accelerometer
2     -201.0  694.0  1906.0  1.711124e+09       3  accelerometer
3     -160.0  674.0  1916.0  1.711124e+09       3  accelerometer
4     -169.0  692.0  1923.0  1.711124e+09       3  accelerometer
...      ...    ...     ...           ...     ...            ...
22331 -332.0  962.0  1777.0  1.711124e+09       3  accelerometer
22332 -324.0  974.0  1775.0  1.711124e+09       3  accelerometer
22333 -328.0  956.0  1760.0  1.711124e+09       3  accelerometer
22334 -316.0  976.0  1782.0  1.711124e+09       3  accelerometer
22335 -320.0  960.0  1777.0  1.711124e+09       3  accelerometer

[22336 rows x 6 columns]

### ANOVA for subject 1

In [18]:
f_val, p_val = f_oneway(df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'], df_bvp_1['values'], df_eda_1['values'], df_temperature_1['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 11871182.458876612, p-value: 0.0

### ANOVA for subject 2

In [19]:
f_val, p_val = f_oneway(df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_bvp_2['values'], df_eda_2['values'], df_temperature_2['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 418224.3115077667, p-value: 0.0

ANOVA for subject 3

In [20]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_bvp_3['values'], df_eda_3['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 2409717.7327204165, p-value: 0.0

ANOVA accelerometer across subjects

In [21]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 1154289.6762410956, p-value: 0.0

ANOVA EDA across subjects

In [22]:
f_val, p_val = f_oneway(df_eda_1['values'], df_eda_2['values'], df_eda_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 6013.11172688598, p-value: 0.0

ANOVA BVP across subjects

In [23]:
f_val, p_val = f_oneway(df_bvp_1['values'], df_bvp_2['values'], df_bvp_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 0.016168231632137337, p-value: 0.9839617764645172

ANOVA temp across subjects

In [24]:
f_val, p_val = f_oneway(df_temperature_1['values'], df_temperature_2['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 4921.554411547795, p-value: 0.0