In [1]:
import os
import pandas as pd
from scipy.stats import f_oneway


folder_path = r'C:\Users\rusha\Desktop\Uni_Freiburg_Notes\MDD\pilot\videos'
sensors = ['accelerometer', 'bvp', 'eda', 'systolicPeaks', 'temperature']

subject_dataframes = {subject: {sensor: pd.DataFrame() for sensor in sensors} for subject in ['1', '2', '3']}

for subject_folder in os.listdir(folder_path):
    subject_path = os.path.join(folder_path, subject_folder)
    if os.path.isdir(subject_path) and subject_folder in subject_dataframes:
        for sensor in sensors:
            file_path = os.path.join(subject_path, f'{sensor}.csv')
            if os.path.isfile(file_path):
                df = pd.read_csv(file_path)
                df['subject'] = subject_folder
                df['sensor'] = sensor

                subject_dataframes[subject_folder][sensor] = df

# subject 1:
df_accelerometer_1 = subject_dataframes['1']['accelerometer']
df_bvp_1 = subject_dataframes['1']['bvp']
df_eda_1 = subject_dataframes['1']['eda']
df_temperature_1 = subject_dataframes['1']['temperature']

# subject 2:
df_accelerometer_2 = subject_dataframes['2']['accelerometer']
df_bvp_2 = subject_dataframes['2']['bvp']
df_eda_2 = subject_dataframes['2']['eda']
df_temperature_2 = subject_dataframes['2']['temperature']

# subject 3:
df_accelerometer_3 = subject_dataframes['3']['accelerometer']
df_bvp_3 = subject_dataframes['3']['bvp']
df_eda_3 = subject_dataframes['3']['eda']
df_temperature_3 = subject_dataframes['3']['temperature']

In [2]:
def merge_dataframes(dfs, on='time'):
    result = dfs.pop(0)
    for df in dfs:
        result = pd.merge(result, df, on=on, how='outer', suffixes=('', '_dup'))
        result = result.loc[:, ~result.columns.duplicated()]
    return result

combined_dataframes = {}
for subject, dfs in subject_dataframes.items():
    for sensor, df in dfs.items():
        if 'time' not in df.columns:

            df['time'] = pd.to_datetime(df.index, unit='s')
    
    combined_df = pd.concat(list(dfs.values()))
 
    combined_dataframes[subject] = combined_df

df_combined_1 = combined_dataframes['1']
df_combined_2 = combined_dataframes['2']
df_combined_3 = combined_dataframes['3']

In [3]:
df_eda_2

        values          time subject sensor
0    -0.029373  1.711367e+09       2    eda
1    -0.028850  1.711367e+09       2    eda
2    -0.029576  1.711367e+09       2    eda
3    -0.031129  1.711367e+09       2    eda
4    -0.030316  1.711367e+09       2    eda
...        ...           ...     ...    ...
4955 -0.000491  1.711368e+09       2    eda
4956 -0.002392  1.711368e+09       2    eda
4957 -0.001521  1.711368e+09       2    eda
4958 -0.002029  1.711368e+09       2    eda
4959 -0.001986  1.711368e+09       2    eda

[4960 rows x 4 columns]

In [4]:
# df_accelerometer_1 = df_accelerometer_1.drop(columns=['subject', 'sensor'])
# df_accelerometer_2 = df_accelerometer_2.drop(columns=['subject', 'sensor'])
# df_accelerometer_3 = df_accelerometer_3.drop(columns=['subject', 'sensor'])
# df_bvp_1 = df_bvp_1.drop(columns=['subject', 'sensor'])
# df_bvp_2 = df_bvp_2.drop(columns=['subject', 'sensor'])
# df_bvp_3 = df_bvp_3.drop(columns=['subject', 'sensor'])
# df_eda_1 = df_eda_1.drop(columns=['subject', 'sensor'])
# df_eda_2 = df_eda_2.drop(columns=['subject', 'sensor'])
# df_eda_3 = df_eda_3.drop(columns=['subject', 'sensor'])
# df_temperature_1 = df_temperature_1.drop(columns=['subject', 'sensor'])
# df_temperature_2 = df_temperature_2.drop(columns=['subject', 'sensor'])
# df_temperature_3 = df_temperature_3.drop(columns=['subject', 'sensor'])

In [5]:
df_accelerometer_3

            x       y       z          time subject         sensor
0      2052.0   383.0   -84.0  1.711369e+09       3  accelerometer
1      2122.0   487.0  -150.0  1.711369e+09       3  accelerometer
2      2126.0   429.0  -262.0  1.711369e+09       3  accelerometer
3      2109.0   208.0  -343.0  1.711369e+09       3  accelerometer
4      2062.0   -15.0  -347.0  1.711369e+09       3  accelerometer
...       ...     ...     ...           ...     ...            ...
79291   777.0  1148.0  1294.0  1.711370e+09       3  accelerometer
79292   826.0  1087.0  1395.0  1.711370e+09       3  accelerometer
79293   841.0  1160.0  1507.0  1.711370e+09       3  accelerometer
79294   806.0   970.0  1480.0  1.711370e+09       3  accelerometer
79295   777.0   933.0  1456.0  1.711370e+09       3  accelerometer

[79296 rows x 6 columns]

### ANOVA for subject 1

In [6]:
f_val, p_val = f_oneway(df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'], df_bvp_1['values'], df_eda_1['values'], df_temperature_1['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 3342386.7683464466, p-value: 0.0

### ANOVA for subject 2

In [7]:
f_val, p_val = f_oneway(df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_bvp_2['values'], df_eda_2['values'], df_temperature_2['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 1540164.6822533451, p-value: 0.0

ANOVA for subject 3

In [8]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_bvp_3['values'], df_eda_3['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 649511.3525419992, p-value: 0.0

ANOVA accelerometer across subjects

In [9]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 2391851.704113809, p-value: 0.0

ANOVA EDA across subjects

In [10]:
f_val, p_val = f_oneway(df_eda_1['values'], df_eda_2['values'], df_eda_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 16224.706560622242, p-value: 0.0

ANOVA BVP across subjects

In [11]:
f_val, p_val = f_oneway(df_bvp_1['values'], df_bvp_2['values'], df_bvp_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 0.12876704326191102, p-value: 0.8791814653478384

ANOVA temp across subjects

In [17]:
f_val, p_val = f_oneway(df_temperature_1['values'], df_temperature_2['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 5884.6325417433745, p-value: 0.0

In [22]:
import math
nan_count = sum(1 for item in df_temperature_3['values'] if math.isnan(item))

print(f"Number of NaNs: {nan_count}")

Number of NaNs: 0