In [13]:
import os
import pandas as pd
from scipy.stats import f_oneway

folder_path = r'C:\Users\rusha\Desktop\Uni_Freiburg_Notes\MDD\pilot\panas'
sensors = ['accelerometer', 'bvp', 'eda', 'systolicPeaks', 'temperature']

subject_dataframes = {subject: {sensor: pd.DataFrame() for sensor in sensors} for subject in ['1', '2', '3']}

for subject_folder in os.listdir(folder_path):
    subject_path = os.path.join(folder_path, subject_folder)
    if os.path.isdir(subject_path) and subject_folder in subject_dataframes:
        for sensor in sensors:
            file_path = os.path.join(subject_path, f'{sensor}.csv')
            if os.path.isfile(file_path):
                df = pd.read_csv(file_path)
                df['subject'] = subject_folder
                df['sensor'] = sensor
  
                subject_dataframes[subject_folder][sensor] = df

# subject 1:
df_accelerometer_1 = subject_dataframes['1']['accelerometer']
df_bvp_1 = subject_dataframes['1']['bvp']
df_eda_1 = subject_dataframes['1']['eda']
df_temperature_1 = subject_dataframes['1']['temperature']

# subject 2:
df_accelerometer_2 = subject_dataframes['2']['accelerometer']
df_bvp_2 = subject_dataframes['2']['bvp']
df_eda_2 = subject_dataframes['2']['eda']
df_temperature_2 = subject_dataframes['2']['temperature']

# subject 3:
df_accelerometer_3 = subject_dataframes['3']['accelerometer']
df_bvp_3 = subject_dataframes['3']['bvp']
df_eda_3 = subject_dataframes['3']['eda']
df_temperature_3 = subject_dataframes['3']['temperature']

In [14]:
def merge_dataframes(dfs, on='time'):
    result = dfs.pop(0)
    for df in dfs:
        result = pd.merge(result, df, on=on, how='outer', suffixes=('', '_dup'))
        result = result.loc[:, ~result.columns.duplicated()]
    return result

combined_dataframes = {}
for subject, dfs in subject_dataframes.items():
 
    for sensor, df in dfs.items():
        if 'time' not in df.columns:
            df['time'] = pd.to_datetime(df.index, unit='s')
    combined_df = pd.concat(list(dfs.values()))

    combined_dataframes[subject] = combined_df

df_combined_1 = combined_dataframes['1']
df_combined_2 = combined_dataframes['2']
df_combined_3 = combined_dataframes['3']

In [15]:
df_eda_2

        values          time subject sensor
0     0.111074  1.711123e+09       2    eda
1     0.111611  1.711123e+09       2    eda
2     0.112018  1.711123e+09       2    eda
3     0.112076  1.711123e+09       2    eda
4     0.112685  1.711123e+09       2    eda
...        ...           ...     ...    ...
1250  0.152467  1.711123e+09       2    eda
1251  0.152380  1.711123e+09       2    eda
1252  0.151770  1.711123e+09       2    eda
1253  0.151683  1.711123e+09       2    eda
1254  0.152090  1.711123e+09       2    eda

[1255 rows x 4 columns]

In [16]:
# df_accelerometer_1 = df_accelerometer_1.drop(columns=['subject', 'sensor'])
# df_accelerometer_2 = df_accelerometer_2.drop(columns=['subject', 'sensor'])
# df_accelerometer_3 = df_accelerometer_3.drop(columns=['subject', 'sensor'])
# df_bvp_1 = df_bvp_1.drop(columns=['subject', 'sensor'])
# df_bvp_2 = df_bvp_2.drop(columns=['subject', 'sensor'])
# df_bvp_3 = df_bvp_3.drop(columns=['subject', 'sensor'])
# df_eda_1 = df_eda_1.drop(columns=['subject', 'sensor'])
# df_eda_2 = df_eda_2.drop(columns=['subject', 'sensor'])
# df_eda_3 = df_eda_3.drop(columns=['subject', 'sensor'])
# df_temperature_1 = df_temperature_1.drop(columns=['subject', 'sensor'])
# df_temperature_2 = df_temperature_2.drop(columns=['subject', 'sensor'])
# df_temperature_3 = df_temperature_3.drop(columns=['subject', 'sensor'])

In [17]:
df_accelerometer_3

           x       y      z          time subject         sensor
0      424.0  1973.0  -22.0  1.711124e+09       3  accelerometer
1      423.0  1971.0  -13.0  1.711124e+09       3  accelerometer
2      431.0  1993.0  -33.0  1.711124e+09       3  accelerometer
3      440.0  2004.0  -30.0  1.711124e+09       3  accelerometer
4      437.0  1994.0  -19.0  1.711124e+09       3  accelerometer
...      ...     ...    ...           ...     ...            ...
19643  747.0  1858.0  204.0  1.711125e+09       3  accelerometer
19644  764.0  1889.0  195.0  1.711125e+09       3  accelerometer
19645  758.0  1888.0  177.0  1.711125e+09       3  accelerometer
19646  744.0  1881.0  191.0  1.711125e+09       3  accelerometer
19647  768.0  1900.0  184.0  1.711125e+09       3  accelerometer

[19648 rows x 6 columns]

### ANOVA for subject 1

In [18]:
f_val, p_val = f_oneway(df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'], df_bvp_1['values'], df_eda_1['values'], df_temperature_1['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 381427.9145329014, p-value: 0.0

### ANOVA for subject 2

In [19]:
f_val, p_val = f_oneway(df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_bvp_2['values'], df_eda_2['values'], df_temperature_2['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 19365.90835100317, p-value: 0.0

ANOVA for subject 3

In [20]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_bvp_3['values'], df_eda_3['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 18933.23290915987, p-value: 0.0

ANOVA accelerometer across subjects

In [21]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 26786.911671132602, p-value: 0.0

ANOVA EDA across subjects

In [22]:
f_val, p_val = f_oneway(df_eda_1['values'], df_eda_2['values'], df_eda_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 35589.74582511024, p-value: 0.0

ANOVA BVP across subjects

In [23]:
f_val, p_val = f_oneway(df_bvp_1['values'], df_bvp_2['values'], df_bvp_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 0.1164221640218434, p-value: 0.8900995774397281

ANOVA temp across subjects

In [24]:
f_val, p_val = f_oneway(df_temperature_1['values'], df_temperature_2['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 23825.097718937857, p-value: 0.0