In [1]:
import os
import pandas as pd
from scipy.stats import f_oneway


folder_path = r'C:\Users\rusha\Desktop\Uni_Freiburg_Notes\MDD\pilot\stroop_test'
sensors = ['accelerometer', 'bvp', 'eda', 'systolicPeaks', 'temperature']

subject_dataframes = {subject: {sensor: pd.DataFrame() for sensor in sensors} for subject in ['1', '2', '3']}

for subject_folder in os.listdir(folder_path):
    subject_path = os.path.join(folder_path, subject_folder)
    if os.path.isdir(subject_path) and subject_folder in subject_dataframes:
        for sensor in sensors:
            file_path = os.path.join(subject_path, f'{sensor}.csv')
            if os.path.isfile(file_path):
                df = pd.read_csv(file_path)
                df['subject'] = subject_folder
                df['sensor'] = sensor

                subject_dataframes[subject_folder][sensor] = df

# subject 1:
df_accelerometer_1 = subject_dataframes['1']['accelerometer']
df_bvp_1 = subject_dataframes['1']['bvp']
df_eda_1 = subject_dataframes['1']['eda']
df_temperature_1 = subject_dataframes['1']['temperature']

# subject 2:
df_accelerometer_2 = subject_dataframes['2']['accelerometer']
df_bvp_2 = subject_dataframes['2']['bvp']
df_eda_2 = subject_dataframes['2']['eda']
df_temperature_2 = subject_dataframes['2']['temperature']

# subject 3:
df_accelerometer_3 = subject_dataframes['3']['accelerometer']
df_bvp_3 = subject_dataframes['3']['bvp']
df_eda_3 = subject_dataframes['3']['eda']
df_temperature_3 = subject_dataframes['3']['temperature']

In [2]:
def merge_dataframes(dfs, on='time'):
    result = dfs.pop(0)
    for df in dfs:
        result = pd.merge(result, df, on=on, how='outer', suffixes=('', '_dup'))
        result = result.loc[:, ~result.columns.duplicated()]
    return result

combined_dataframes = {}
for subject, dfs in subject_dataframes.items():
    for sensor, df in dfs.items():
        if 'time' not in df.columns:

            df['time'] = pd.to_datetime(df.index, unit='s')
    
    combined_df = pd.concat(list(dfs.values()))
 
    combined_dataframes[subject] = combined_df

df_combined_1 = combined_dataframes['1']
df_combined_2 = combined_dataframes['2']
df_combined_3 = combined_dataframes['3']

In [3]:
df_eda_2

       values          time subject sensor
0    0.138929  1.711123e+09       2    eda
1    0.139611  1.711123e+09       2    eda
2    0.140511  1.711123e+09       2    eda
3    0.141643  1.711123e+09       2    eda
4    0.141004  1.711123e+09       2    eda
..        ...           ...     ...    ...
655  0.175996  1.711123e+09       2    eda
656  0.175605  1.711123e+09       2    eda
657  0.175938  1.711123e+09       2    eda
658  0.175967  1.711123e+09       2    eda
659  0.176374  1.711123e+09       2    eda

[660 rows x 4 columns]

In [4]:
# df_accelerometer_1 = df_accelerometer_1.drop(columns=['subject', 'sensor'])
# df_accelerometer_2 = df_accelerometer_2.drop(columns=['subject', 'sensor'])
# df_accelerometer_3 = df_accelerometer_3.drop(columns=['subject', 'sensor'])
# df_bvp_1 = df_bvp_1.drop(columns=['subject', 'sensor'])
# df_bvp_2 = df_bvp_2.drop(columns=['subject', 'sensor'])
# df_bvp_3 = df_bvp_3.drop(columns=['subject', 'sensor'])
# df_eda_1 = df_eda_1.drop(columns=['subject', 'sensor'])
# df_eda_2 = df_eda_2.drop(columns=['subject', 'sensor'])
# df_eda_3 = df_eda_3.drop(columns=['subject', 'sensor'])
# df_temperature_1 = df_temperature_1.drop(columns=['subject', 'sensor'])
# df_temperature_2 = df_temperature_2.drop(columns=['subject', 'sensor'])
# df_temperature_3 = df_temperature_3.drop(columns=['subject', 'sensor'])

In [5]:
df_accelerometer_3

           x       y       z          time subject         sensor
0      439.0  1968.0   282.0  1.711125e+09       3  accelerometer
1      467.0  1958.0   293.0  1.711125e+09       3  accelerometer
2      474.0  1969.0   277.0  1.711125e+09       3  accelerometer
3      460.0  1970.0   282.0  1.711125e+09       3  accelerometer
4      467.0  1958.0   281.0  1.711125e+09       3  accelerometer
...      ...     ...     ...           ...     ...            ...
12027  453.0  1033.0  1701.0  1.711125e+09       3  accelerometer
12028  454.0  1032.0  1703.0  1.711125e+09       3  accelerometer
12029  458.0  1032.0  1697.0  1.711125e+09       3  accelerometer
12030  460.0  1029.0  1702.0  1.711125e+09       3  accelerometer
12031  443.0  1038.0  1710.0  1.711125e+09       3  accelerometer

[12032 rows x 6 columns]

### ANOVA for subject 1

In [6]:
f_val, p_val = f_oneway(df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'], df_bvp_1['values'], df_eda_1['values'], df_temperature_1['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 37122.07902555514, p-value: 0.0

### ANOVA for subject 2

In [7]:
f_val, p_val = f_oneway(df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_bvp_2['values'], df_eda_2['values'], df_temperature_2['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 16333.103227467735, p-value: 0.0

ANOVA for subject 3

In [8]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_bvp_3['values'], df_eda_3['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 51435.197544298506, p-value: 0.0

ANOVA accelerometer across subjects

In [9]:
f_val, p_val = f_oneway(df_accelerometer_3['x'], df_accelerometer_3['y'], df_accelerometer_3['z'], df_accelerometer_2['x'], df_accelerometer_2['y'], df_accelerometer_2['z'], df_accelerometer_1['x'], df_accelerometer_1['y'], df_accelerometer_1['z'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 23541.250908618837, p-value: 0.0

ANOVA EDA across subjects

In [10]:
f_val, p_val = f_oneway(df_eda_1['values'], df_eda_2['values'], df_eda_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 1597.0151864111758, p-value: 0.0

ANOVA BVP across subjects

In [11]:
f_val, p_val = f_oneway(df_bvp_1['values'], df_bvp_2['values'], df_bvp_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 0.010307055613374397, p-value: 0.9897458832481446

ANOVA temp across subjects

In [12]:
f_val, p_val = f_oneway(df_temperature_1['values'], df_temperature_2['values'], df_temperature_3['values'])
print(f"F-statistic: {f_val}, p-value: {p_val}")

F-statistic: 73532.71325885603, p-value: 0.0